name: decomfl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10

  - conda-forge::accelerate=0.33
  - conda-forge::datasets=2.19
  - conda-forge::peft=0.12
  - conda-forge::transformers=4.41
  - conda-forge::pydantic=2.10.3
  - conda-forge::pydantic-settings=2.7.0

  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch=2.3
  - pytorch::torchvision=0.18

  - numpy=1.23
  - tensorboardx=2.6
  - tqdm=4.66
