name: zoo
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.3.11=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.13=h2bbff1b_0
  - pip=23.3.1=py310haa95532_0
  - python=3.10.14=he1021f5_0
  - setuptools=68.2.2=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - absl-py==2.1.0
      - alabaster==0.7.16
      - arrow==1.3.0
      - astroid==3.1.0
      - asttokens==2.4.1
      - atomicwrites==1.4.1
      - attrs==23.2.0
      - autopep8==2.0.4
      - babel==2.14.0
      - backports-tarfile==1.1.0
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.3
      - binaryornot==0.4.4
      - black==24.4.0
      - bleach==6.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - comm==0.2.2
      - cookiecutter==2.6.0
      - cryptography==42.0.5
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diff-match-patch==20230430
      - dill==0.3.8
      - docstring-to-markdown==0.15
      - docutils==0.21.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.9.0
      - flake8==7.0.0
      - fsspec==2023.4.0
      - grpcio==1.62.1
      - idna==3.7
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - inflection==0.5.1
      - iniconfig==2.0.0
      - intervaltree==3.1.0
      - ipykernel==6.29.4
      - ipython==8.23.0
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jedi==0.19.1
      - jellyfish==1.0.3
      - jinja2==3.1.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keyring==25.1.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.26.3
      - numpydoc==1.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - paramiko==3.4.0
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - prompt-toolkit==3.0.43
      - protobuf==5.26.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycodestyle==2.11.1
      - pycparser==2.22
      - pydocstyle==6.3.0
      - pyflakes==3.2.0
      - pygments==2.17.2
      - pylint==3.1.0
      - pylint-venv==3.0.3
      - pyls-spyder==0.4.0
      - pynacl==1.5.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtwebengine==5.15.6
      - pyqtwebengine-qt5==5.15.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-server==1.11.0
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pytz==2024.1
      - pywin32==306
      - pywin32-ctypes==0.2.2
      - pyyaml==6.0.1
      - pyzmq==26.0.0
      - qdarkstyle==3.2.3
      - qstylizer==0.2.3
      - qtawesome==1.3.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.34.0
      - requests==2.31.0
      - rich==13.7.1
      - rope==1.13.0
      - rpds-py==0.18.0
      - rtree==1.2.0
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sphinx==7.3.6
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - spyder==5.5.4
      - spyder-kernels==2.5.1
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tbparse==0.0.8
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - text-unidecode==1.3
      - textdistance==4.6.1
      - three-merge==0.1.1
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomlkit==0.12.4
      - torch==2.2.2+cu121
      - torchaudio==2.2.2+cu121
      - torchvision==0.17.2+cu121
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - ujson==5.9.0
      - urllib3==2.2.1
      - watchdog==4.0.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.0.2
      - whatthepatch==1.0.5
      - yapf==0.40.2
      - zipp==3.18.1
